---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "kommander.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.name }}"
    heritage: "{{ .Release.Service }}"
    servicemonitor.kubeaddons.mesosphere.io/path: metrics
spec:
  ports:
    - name: metrics
      port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: {{ template "kommander.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
